name = "Glitch Dream"

[colors.main_bg]     # Backlit black with a purple tint
r = 20
g = 10
b = 30

[colors.main_fg]     # Glowing lavender
r = 200
g = 160
b = 255

[colors.accent_bg]   # Magenta burst
r = 255
g = 20
b = 147

[colors.accent_fg]   # Icy white
r = 220
g = 255
b = 255

[colors.playing]     # Electric cyan
r = 0
g = 255
b = 255

[colors.playlist]    # Neon green
r = 0
g = 255
b = 127

[colors.highlight_bg]
r = 255
g = 255
b = 0

[colors.highlight_fg]
r = 0
g = 0
b = 0